version: '3'

services:
    mongo:
        image: mongo
        restart: always
        container_name: admin-app-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12345
            MONGO_INITDB_DATABASE: admin_app
        volumes:
            - mongo_db:/data/db
        ports:
            - "27019:27017"
        networks:
            - admin-app

volumes:
    mongo_db:

networks:
    admin-app:
